/*
 * generated by Xtext 2.18.0
 */
package mic.model_code_synchronization


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MappingDSLRuntimeModule extends AbstractMappingDSLRuntimeModule {
}
