/*
 * generated by Xtext 2.18.0
 */
package mic.model_code_synchronization


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MappingDSLStandaloneSetup extends MappingDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new MappingDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
