/*
 * generated by Xtext 2.18.0
 */
package mic.model_code_synchronization.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMappingDSLScopeProvider extends DelegatingScopeProvider {
}
