/*
 * generated by Xtext 2.18.0
 */
package mic.model_code_synchronization.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MappingDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("mic/model_code_synchronization/parser/antlr/internal/InternalMappingDSL.tokens");
	}
}
