/*
 * generated by Xtext 2.18.0
 */
package mic.model_code_synchronization.parser.antlr;

import com.google.inject.Inject;
import mic.model_code_synchronization.parser.antlr.internal.InternalMappingDSLParser;
import mic.model_code_synchronization.services.MappingDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MappingDSLParser extends AbstractAntlrParser {

	@Inject
	private MappingDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMappingDSLParser createParser(XtextTokenStream stream) {
		return new InternalMappingDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MappingDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MappingDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
