/**
 * generated by Xtext 2.18.0
 */
package mic.model_code_synchronization.mappingDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Codestructure</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mic.model_code_synchronization.mappingDSL.Codestructure#getCodestructure <em>Codestructure</em>}</li>
 * </ul>
 *
 * @see mic.model_code_synchronization.mappingDSL.MappingDSLPackage#getCodestructure()
 * @model
 * @generated
 */
public interface Codestructure extends EObject
{
  /**
   * Returns the value of the '<em><b>Codestructure</b></em>' attribute.
   * The literals are from the enumeration {@link mic.model_code_synchronization.mappingDSL.CodeStructureType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Codestructure</em>' attribute.
   * @see mic.model_code_synchronization.mappingDSL.CodeStructureType
   * @see #setCodestructure(CodeStructureType)
   * @see mic.model_code_synchronization.mappingDSL.MappingDSLPackage#getCodestructure_Codestructure()
   * @model
   * @generated
   */
  CodeStructureType getCodestructure();

  /**
   * Sets the value of the '{@link mic.model_code_synchronization.mappingDSL.Codestructure#getCodestructure <em>Codestructure</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Codestructure</em>' attribute.
   * @see mic.model_code_synchronization.mappingDSL.CodeStructureType
   * @see #getCodestructure()
   * @generated
   */
  void setCodestructure(CodeStructureType value);

} // Codestructure
