/**
 * generated by Xtext 2.18.0
 */
package mic.model_code_synchronization.mappingDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integration Mechanism Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getCodestructure <em>Codestructure</em>}</li>
 *   <li>{@link mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getModelelement <em>Modelelement</em>}</li>
 *   <li>{@link mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getCondition <em>Condition</em>}</li>
 *   <li>{@link mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getMapping <em>Mapping</em>}</li>
 * </ul>
 *
 * @see mic.model_code_synchronization.mappingDSL.MappingDSLPackage#getIntegrationMechanismDeclaration()
 * @model
 * @generated
 */
public interface IntegrationMechanismDeclaration extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see mic.model_code_synchronization.mappingDSL.MappingDSLPackage#getIntegrationMechanismDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Codestructure</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Codestructure</em>' containment reference.
   * @see #setCodestructure(Codestructure)
   * @see mic.model_code_synchronization.mappingDSL.MappingDSLPackage#getIntegrationMechanismDeclaration_Codestructure()
   * @model containment="true"
   * @generated
   */
  Codestructure getCodestructure();

  /**
   * Sets the value of the '{@link mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getCodestructure <em>Codestructure</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Codestructure</em>' containment reference.
   * @see #getCodestructure()
   * @generated
   */
  void setCodestructure(Codestructure value);

  /**
   * Returns the value of the '<em><b>Modelelement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modelelement</em>' containment reference.
   * @see #setModelelement(ModelElement)
   * @see mic.model_code_synchronization.mappingDSL.MappingDSLPackage#getIntegrationMechanismDeclaration_Modelelement()
   * @model containment="true"
   * @generated
   */
  ModelElement getModelelement();

  /**
   * Sets the value of the '{@link mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getModelelement <em>Modelelement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Modelelement</em>' containment reference.
   * @see #getModelelement()
   * @generated
   */
  void setModelelement(ModelElement value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Condition)
   * @see mic.model_code_synchronization.mappingDSL.MappingDSLPackage#getIntegrationMechanismDeclaration_Condition()
   * @model containment="true"
   * @generated
   */
  Condition getCondition();

  /**
   * Sets the value of the '{@link mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Condition value);

  /**
   * Returns the value of the '<em><b>Mapping</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mapping</em>' containment reference.
   * @see #setMapping(Mapping)
   * @see mic.model_code_synchronization.mappingDSL.MappingDSLPackage#getIntegrationMechanismDeclaration_Mapping()
   * @model containment="true"
   * @generated
   */
  Mapping getMapping();

  /**
   * Sets the value of the '{@link mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getMapping <em>Mapping</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mapping</em>' containment reference.
   * @see #getMapping()
   * @generated
   */
  void setMapping(Mapping value);

} // IntegrationMechanismDeclaration
