/**
 * generated by Xtext 2.18.0
 */
package mic.model_code_synchronization.mappingDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see mic.model_code_synchronization.mappingDSL.MappingDSLFactory
 * @model kind="package"
 * @generated
 */
public interface MappingDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mappingDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.model_code_synchronization.mic/MappingDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mappingDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MappingDSLPackage eINSTANCE = mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link mic.model_code_synchronization.mappingDSL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mic.model_code_synchronization.mappingDSL.impl.ModelImpl
   * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mic.model_code_synchronization.mappingDSL.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mic.model_code_synchronization.mappingDSL.impl.AbstractElementImpl
   * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link mic.model_code_synchronization.mappingDSL.impl.IntegrationMechanismDeclarationImpl <em>Integration Mechanism Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mic.model_code_synchronization.mappingDSL.impl.IntegrationMechanismDeclarationImpl
   * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getIntegrationMechanismDeclaration()
   * @generated
   */
  int INTEGRATION_MECHANISM_DECLARATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGRATION_MECHANISM_DECLARATION__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Codestructure</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGRATION_MECHANISM_DECLARATION__CODESTRUCTURE = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Modelelement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGRATION_MECHANISM_DECLARATION__MODELELEMENT = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGRATION_MECHANISM_DECLARATION__CONDITION = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Mapping</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGRATION_MECHANISM_DECLARATION__MAPPING = ABSTRACT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Integration Mechanism Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGRATION_MECHANISM_DECLARATION_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link mic.model_code_synchronization.mappingDSL.impl.CodestructureImpl <em>Codestructure</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mic.model_code_synchronization.mappingDSL.impl.CodestructureImpl
   * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getCodestructure()
   * @generated
   */
  int CODESTRUCTURE = 3;

  /**
   * The feature id for the '<em><b>Codestructure</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODESTRUCTURE__CODESTRUCTURE = 0;

  /**
   * The number of structural features of the '<em>Codestructure</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODESTRUCTURE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mic.model_code_synchronization.mappingDSL.impl.ModelElementImpl <em>Model Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mic.model_code_synchronization.mappingDSL.impl.ModelElementImpl
   * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getModelElement()
   * @generated
   */
  int MODEL_ELEMENT = 4;

  /**
   * The feature id for the '<em><b>Modelelement</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_ELEMENT__MODELELEMENT = 0;

  /**
   * The number of structural features of the '<em>Model Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mic.model_code_synchronization.mappingDSL.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mic.model_code_synchronization.mappingDSL.impl.ConditionImpl
   * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 5;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__CONDITION = 0;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mic.model_code_synchronization.mappingDSL.impl.MappingImpl <em>Mapping</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mic.model_code_synchronization.mappingDSL.impl.MappingImpl
   * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getMapping()
   * @generated
   */
  int MAPPING = 6;

  /**
   * The feature id for the '<em><b>Mapping</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING__MAPPING = 0;

  /**
   * The number of structural features of the '<em>Mapping</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mic.model_code_synchronization.mappingDSL.CodeStructureType <em>Code Structure Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mic.model_code_synchronization.mappingDSL.CodeStructureType
   * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getCodeStructureType()
   * @generated
   */
  int CODE_STRUCTURE_TYPE = 7;

  /**
   * The meta object id for the '{@link mic.model_code_synchronization.mappingDSL.ModelElementType <em>Model Element Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mic.model_code_synchronization.mappingDSL.ModelElementType
   * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getModelElementType()
   * @generated
   */
  int MODEL_ELEMENT_TYPE = 8;


  /**
   * Returns the meta object for class '{@link mic.model_code_synchronization.mappingDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see mic.model_code_synchronization.mappingDSL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link mic.model_code_synchronization.mappingDSL.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see mic.model_code_synchronization.mappingDSL.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link mic.model_code_synchronization.mappingDSL.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see mic.model_code_synchronization.mappingDSL.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for class '{@link mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration <em>Integration Mechanism Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Integration Mechanism Declaration</em>'.
   * @see mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration
   * @generated
   */
  EClass getIntegrationMechanismDeclaration();

  /**
   * Returns the meta object for the attribute '{@link mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getName()
   * @see #getIntegrationMechanismDeclaration()
   * @generated
   */
  EAttribute getIntegrationMechanismDeclaration_Name();

  /**
   * Returns the meta object for the containment reference '{@link mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getCodestructure <em>Codestructure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Codestructure</em>'.
   * @see mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getCodestructure()
   * @see #getIntegrationMechanismDeclaration()
   * @generated
   */
  EReference getIntegrationMechanismDeclaration_Codestructure();

  /**
   * Returns the meta object for the containment reference '{@link mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getModelelement <em>Modelelement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Modelelement</em>'.
   * @see mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getModelelement()
   * @see #getIntegrationMechanismDeclaration()
   * @generated
   */
  EReference getIntegrationMechanismDeclaration_Modelelement();

  /**
   * Returns the meta object for the containment reference '{@link mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getCondition()
   * @see #getIntegrationMechanismDeclaration()
   * @generated
   */
  EReference getIntegrationMechanismDeclaration_Condition();

  /**
   * Returns the meta object for the containment reference '{@link mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getMapping <em>Mapping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mapping</em>'.
   * @see mic.model_code_synchronization.mappingDSL.IntegrationMechanismDeclaration#getMapping()
   * @see #getIntegrationMechanismDeclaration()
   * @generated
   */
  EReference getIntegrationMechanismDeclaration_Mapping();

  /**
   * Returns the meta object for class '{@link mic.model_code_synchronization.mappingDSL.Codestructure <em>Codestructure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Codestructure</em>'.
   * @see mic.model_code_synchronization.mappingDSL.Codestructure
   * @generated
   */
  EClass getCodestructure();

  /**
   * Returns the meta object for the attribute '{@link mic.model_code_synchronization.mappingDSL.Codestructure#getCodestructure <em>Codestructure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Codestructure</em>'.
   * @see mic.model_code_synchronization.mappingDSL.Codestructure#getCodestructure()
   * @see #getCodestructure()
   * @generated
   */
  EAttribute getCodestructure_Codestructure();

  /**
   * Returns the meta object for class '{@link mic.model_code_synchronization.mappingDSL.ModelElement <em>Model Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model Element</em>'.
   * @see mic.model_code_synchronization.mappingDSL.ModelElement
   * @generated
   */
  EClass getModelElement();

  /**
   * Returns the meta object for the attribute '{@link mic.model_code_synchronization.mappingDSL.ModelElement#getModelelement <em>Modelelement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Modelelement</em>'.
   * @see mic.model_code_synchronization.mappingDSL.ModelElement#getModelelement()
   * @see #getModelElement()
   * @generated
   */
  EAttribute getModelElement_Modelelement();

  /**
   * Returns the meta object for class '{@link mic.model_code_synchronization.mappingDSL.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see mic.model_code_synchronization.mappingDSL.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the attribute '{@link mic.model_code_synchronization.mappingDSL.Condition#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see mic.model_code_synchronization.mappingDSL.Condition#getCondition()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Condition();

  /**
   * Returns the meta object for class '{@link mic.model_code_synchronization.mappingDSL.Mapping <em>Mapping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mapping</em>'.
   * @see mic.model_code_synchronization.mappingDSL.Mapping
   * @generated
   */
  EClass getMapping();

  /**
   * Returns the meta object for the attribute '{@link mic.model_code_synchronization.mappingDSL.Mapping#getMapping <em>Mapping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mapping</em>'.
   * @see mic.model_code_synchronization.mappingDSL.Mapping#getMapping()
   * @see #getMapping()
   * @generated
   */
  EAttribute getMapping_Mapping();

  /**
   * Returns the meta object for enum '{@link mic.model_code_synchronization.mappingDSL.CodeStructureType <em>Code Structure Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Code Structure Type</em>'.
   * @see mic.model_code_synchronization.mappingDSL.CodeStructureType
   * @generated
   */
  EEnum getCodeStructureType();

  /**
   * Returns the meta object for enum '{@link mic.model_code_synchronization.mappingDSL.ModelElementType <em>Model Element Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Model Element Type</em>'.
   * @see mic.model_code_synchronization.mappingDSL.ModelElementType
   * @generated
   */
  EEnum getModelElementType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MappingDSLFactory getMappingDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link mic.model_code_synchronization.mappingDSL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mic.model_code_synchronization.mappingDSL.impl.ModelImpl
     * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link mic.model_code_synchronization.mappingDSL.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mic.model_code_synchronization.mappingDSL.impl.AbstractElementImpl
     * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '{@link mic.model_code_synchronization.mappingDSL.impl.IntegrationMechanismDeclarationImpl <em>Integration Mechanism Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mic.model_code_synchronization.mappingDSL.impl.IntegrationMechanismDeclarationImpl
     * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getIntegrationMechanismDeclaration()
     * @generated
     */
    EClass INTEGRATION_MECHANISM_DECLARATION = eINSTANCE.getIntegrationMechanismDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTEGRATION_MECHANISM_DECLARATION__NAME = eINSTANCE.getIntegrationMechanismDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Codestructure</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTEGRATION_MECHANISM_DECLARATION__CODESTRUCTURE = eINSTANCE.getIntegrationMechanismDeclaration_Codestructure();

    /**
     * The meta object literal for the '<em><b>Modelelement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTEGRATION_MECHANISM_DECLARATION__MODELELEMENT = eINSTANCE.getIntegrationMechanismDeclaration_Modelelement();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTEGRATION_MECHANISM_DECLARATION__CONDITION = eINSTANCE.getIntegrationMechanismDeclaration_Condition();

    /**
     * The meta object literal for the '<em><b>Mapping</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTEGRATION_MECHANISM_DECLARATION__MAPPING = eINSTANCE.getIntegrationMechanismDeclaration_Mapping();

    /**
     * The meta object literal for the '{@link mic.model_code_synchronization.mappingDSL.impl.CodestructureImpl <em>Codestructure</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mic.model_code_synchronization.mappingDSL.impl.CodestructureImpl
     * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getCodestructure()
     * @generated
     */
    EClass CODESTRUCTURE = eINSTANCE.getCodestructure();

    /**
     * The meta object literal for the '<em><b>Codestructure</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CODESTRUCTURE__CODESTRUCTURE = eINSTANCE.getCodestructure_Codestructure();

    /**
     * The meta object literal for the '{@link mic.model_code_synchronization.mappingDSL.impl.ModelElementImpl <em>Model Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mic.model_code_synchronization.mappingDSL.impl.ModelElementImpl
     * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getModelElement()
     * @generated
     */
    EClass MODEL_ELEMENT = eINSTANCE.getModelElement();

    /**
     * The meta object literal for the '<em><b>Modelelement</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL_ELEMENT__MODELELEMENT = eINSTANCE.getModelElement_Modelelement();

    /**
     * The meta object literal for the '{@link mic.model_code_synchronization.mappingDSL.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mic.model_code_synchronization.mappingDSL.impl.ConditionImpl
     * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__CONDITION = eINSTANCE.getCondition_Condition();

    /**
     * The meta object literal for the '{@link mic.model_code_synchronization.mappingDSL.impl.MappingImpl <em>Mapping</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mic.model_code_synchronization.mappingDSL.impl.MappingImpl
     * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getMapping()
     * @generated
     */
    EClass MAPPING = eINSTANCE.getMapping();

    /**
     * The meta object literal for the '<em><b>Mapping</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAPPING__MAPPING = eINSTANCE.getMapping_Mapping();

    /**
     * The meta object literal for the '{@link mic.model_code_synchronization.mappingDSL.CodeStructureType <em>Code Structure Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mic.model_code_synchronization.mappingDSL.CodeStructureType
     * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getCodeStructureType()
     * @generated
     */
    EEnum CODE_STRUCTURE_TYPE = eINSTANCE.getCodeStructureType();

    /**
     * The meta object literal for the '{@link mic.model_code_synchronization.mappingDSL.ModelElementType <em>Model Element Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mic.model_code_synchronization.mappingDSL.ModelElementType
     * @see mic.model_code_synchronization.mappingDSL.impl.MappingDSLPackageImpl#getModelElementType()
     * @generated
     */
    EEnum MODEL_ELEMENT_TYPE = eINSTANCE.getModelElementType();

  }

} //MappingDSLPackage
