/**
 * generated by Xtext 2.18.0
 */
package mic.model_code_synchronization.mappingDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mic.model_code_synchronization.mappingDSL.Mapping#getMapping <em>Mapping</em>}</li>
 * </ul>
 *
 * @see mic.model_code_synchronization.mappingDSL.MappingDSLPackage#getMapping()
 * @model
 * @generated
 */
public interface Mapping extends EObject
{
  /**
   * Returns the value of the '<em><b>Mapping</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mapping</em>' attribute.
   * @see #setMapping(String)
   * @see mic.model_code_synchronization.mappingDSL.MappingDSLPackage#getMapping_Mapping()
   * @model
   * @generated
   */
  String getMapping();

  /**
   * Sets the value of the '{@link mic.model_code_synchronization.mappingDSL.Mapping#getMapping <em>Mapping</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mapping</em>' attribute.
   * @see #getMapping()
   * @generated
   */
  void setMapping(String value);

} // Mapping
