/**
 * generated by Xtext 2.18.0
 */
package mic.model_code_synchronization.mappingDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mic.model_code_synchronization.mappingDSL.ModelElement#getModelelement <em>Modelelement</em>}</li>
 * </ul>
 *
 * @see mic.model_code_synchronization.mappingDSL.MappingDSLPackage#getModelElement()
 * @model
 * @generated
 */
public interface ModelElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Modelelement</b></em>' attribute.
   * The literals are from the enumeration {@link mic.model_code_synchronization.mappingDSL.ModelElementType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modelelement</em>' attribute.
   * @see mic.model_code_synchronization.mappingDSL.ModelElementType
   * @see #setModelelement(ModelElementType)
   * @see mic.model_code_synchronization.mappingDSL.MappingDSLPackage#getModelElement_Modelelement()
   * @model
   * @generated
   */
  ModelElementType getModelelement();

  /**
   * Sets the value of the '{@link mic.model_code_synchronization.mappingDSL.ModelElement#getModelelement <em>Modelelement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Modelelement</em>' attribute.
   * @see mic.model_code_synchronization.mappingDSL.ModelElementType
   * @see #getModelelement()
   * @generated
   */
  void setModelelement(ModelElementType value);

} // ModelElement
