/*
 * generated by Xtext 2.18.0
 */
package mic.model_code_synchronization.ide


/**
 * Use this class to register ide components.
 */
class MappingDSLIdeModule extends AbstractMappingDSLIdeModule {
}
