/*
 * generated by Xtext 2.18.0
 */
package mic.model_code_synchronization.ui.tests;

import com.google.inject.Injector;
import mic.model_code_synchronization.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MappingDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("mic.model_code_synchronization.MappingDSL");
	}

}
