/*
 * generated by Xtext 2.18.0
 */
package mic.model_code_synchronization.ui;

import com.google.inject.Injector;
import mic.model_code_synchronization.dsl.ui.internal.DslActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MappingDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(DslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		DslActivator activator = DslActivator.getInstance();
		return activator != null ? activator.getInjector(DslActivator.MIC_MODEL_CODE_SYNCHRONIZATION_MAPPINGDSL) : null;
	}

}
